export const jobProjects = [
    {
        "title": "BotGauge Beta Testing",
        "imagePath":null,
        "link": "https://botgauge.com/",
        "featured": false,
        "timeline": "Present",
        "tag":["Internship","Frontend Development"],
        "madeAt": "BotGauge",
        "description": "BotGauge is a Gen AI-powered low-code test automation platform. With BotGauge, users can write test case scenarios in English and automate them with AI assistance giving an increased productivity of 10x and reducing testing costs by 45%",
        "skill": ["React", "JavaScript", "Redux", "Ant Design"],
    },
    {
        "title": "ashaikh",
        "imagePath":"/projects/ashaikh.png",
        "link": "https://github.com/PerHac13/ashaikh",
        "featured": true,
        "timeline": "May 2024",
        "tag":["Portfolio","Frontend Development"],
        "madeAt": "",
        "description": "This is my portfolio website that I have built to showcase my skills and projects.",
        "skill": ["React", "TypeScript", "TailwindCSS", "nextJS","Vercel"],
    },
    {
        "title": "OPCODE",
        "imagePath":"/projects/opcode.png",
        "link": "https://osf-ten.vercel.app/",
        "featured": true,
        "timeline": "Mar 2024",
        "tag":["Team Lead","Organizer","Open Source", "Frontend Development"],
        "madeAt": "Technical Board (IIITBH)",
        "description": "OPCODE is our university's inaugural Intra-College Open Source Fest. Serving as an intermediary platform connecting contributors and organizers, OPCODE facilitates registration, project listing, and leaderboard tracking.",
        "skill": ["React", "JavaScript", "TypeScript", "TailwindCSS", "Vercel", "Renderer"],
    },
    {
        "title": "ChiChat",
        "imagePath":null,
        "link": "https://github.com/PerHac13/ChitChat",
        "featured": false,
        "timeline": "Feb 2024",
        "tag":["Self Project","Backend Development"],
        "madeAt": "",
        "description": "ChiChat is a chat application that is built using socket.io and express. It provides a platform for users to chat with each other in real-time.",
        "skill": ["Node.js", "Express","MongoDB", "Socket.io", "JavaScript", "React", "TailwindCSS", "DaisyUI"],
    },
    {
        "title":"BookStore",
        "imagePath":null,
        "link": "https://github.com/PerHac13/BookStore-MERN-Stack",
        "featured": false,
        "timeline": "Feb 2024",
        "tag":["Self Project","Full Stack Development"],
        "madeAt": "IIIT-Bhagalpur",
        "description": "BookStore is a platform that provides a interface to the user to do simple CRUD operation.",
        "skill": ["React","TailwindCSS","Node.js","Express","MongoDB"],
    },
    {
        "title": "Jotion",
        "imagePath":"/projects/jotion.png",
        "link": "https://jotion-note-taking-app-sigma.vercel.app/",
        "featured": true,
        "timeline": "Dec 2023",
        "tag":["Self Project","Full Stack Development"],
        "madeAt": "",
        "description": "Jotion is a platform that provides a interface to the user to create and manage their notes and tasks. Along with that, they can publish their notes and tasks to the public.",
        "skill": ["React", "TypeScript", "TailwindCSS","Shadui", "ConvexDB", "Vercel"],
    },
    
    {
        "title":"Portfolio",
        "imagePath":null,
        "link": "https://perhac13.github.io/Portfolio/",
        "featured": false,
        "timeline": "Dec 2023",
        "tag":["Self Project","Frontend Development", "not finished"],
        "madeAt": "",
        "description": "This is my portfolio website version 2 that I have built to showcase my skills and projects.",
        "skill": ["React","CSS","JavaScript"],
    },
    {
        "title":"SuperMarket Billing System",
        "imagePath":null,
        "link": "https://github.com/PerHac13/SuperMarket-Billing-System",
        "featured": false,
        "timeline": "Oct 2023",
        "tag":["Self Project","Command Line Interface"],
        "madeAt": "IIIT-Bhagalpur",
        "description": "SuperMarket Billing System is a simple CLI based application that is used to generate bills for the customers, mantain the inventory for seller.",
        "skill": ["C++", "OOPs", "Data Structure", "File Handling"],
    },
    {
        "title":"Hasher",
        "imagePath":null,
        "link": "https://github.com/PerHac13/hasher",
        "featured": false,
        "timeline": "Sept 2023",
        "tag":["Self Project","Cyber Security"],
        "madeAt": "Hackalite (IIITBH)",
        "description":"It is a powerful cybersecurity tool, created for educational purposes, aiming to illustrate the ease with which weak passwords can be cracked timeline stored as unsalted cryptographic hashes.",
        "skill": ["Python", "Scripting", "Wordlist", "bash"],
    },
    {
        "title":"Enyugma23",
        "imagePath":null,
        "link": null,
        "featured": false,
        "timeline": "Jul 2023",
        "tag":["Contributor","Frontend Development"],
        "madeAt": "GymKhana (IIITBH)",
        "description": "Enyugma23 is our university's annual techno-cultural fest. I have contributed to the frontend development of the website.",
        "skill": ["React","JavaScript","TailwindCSS"],
    },
    {
        "title":"CryptoCraze",
        "imagePath":null,
        "link": "https://perhac13.github.io/CryptoCraze/",
        "featured": false,
        "timeline": "Apr 2023",
        "tag":["Solving for India","Frontend Development", "Hackathon", "Blockchain"],
        "madeAt": "Hackathon (GFG)",
        "description": "CryptoCraze is a platform created for my first ever hackathon that provides a interface to the user to get the latest information about fundamental of Blockchain.",
        "skill": ["HTML","CSS"],
    },
    {
        "title":"Personal Website",
        "imagePath":null,
        "link": "https://perhac13.github.io/Personal_Website-WD/",
        "featured": false,
        "timeline": "Feb 2023",
        "tag":["Self Project","Firstever"],
        "madeAt": "",
        "description": "This is my first ever website that I have built to showcase my skills and projects.",
        "skill": ["HTML","CSS"],
    }
]